export const ADD_TO_CART = 'add_to_cart'
export const MINUS_CART_ITEM_QUANTITY = 'minus_item_cart_quantity'
export const REMOVE_CART_ITEM = 'remove_cart_item'
export const ENTER_FULL_NAME = 'enter_full_name'
export const ENTER_PHONE_NUMBER = 'enter_phone_number'
export const ENTER_ADDRESS = 'enter_address'
export const SUBMIT_CART = 'submit_cart'